project:
  type: website
  output-dir: docs
  resources:
    - pdfs/
    
bibliography: references.bib
csl: ieee.csl

website:
  title: "Joel R. Pradines"
  navbar:
    background: primary 
    foreground: light
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - text: Software
        menu:
          - text: "EdgeCount Package (R)"
            href: https://joelRMath.github.io/EdgeCount/
          - text: "Heparan Sulfate (Java)"
            href: https://joelRMath.github.io/heparan-sulfate/
      - icon: github
        href: https://github.com/joelRMath
      - icon: envelope
        href: mailto:joelRMath@gmail.com

format:
  html:
    theme: cosmo  
    fontsize: 1.1em
    css: styles.css
    include-after-body: footer.html
    toc: true



